# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'Terra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Terra
 pod 'Firebase/Firestore'
 pod 'FirebaseUI/Storage'
 pod 'MaterialComponents/BottomNavigation'
 pod 'MaterialComponents/FlexibleHeader'
 pod 'Mapbox-iOS-SDK', '~> 6.0.0'
 pod 'SnapKit', '~> 5.0.1'

  target 'TerraTests' do

    inherit! :search_paths
    # Pods for testing
  end

end
