# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Terra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Terra
 pod 'Kingfisher', '~> 5.13'
 pod 'Firebase/Auth'
 pod 'Firebase/Firestore'
 pod 'Firebase/Storage'
 pod 'FirebaseUI/Storage'
 


  target 'TerraTests' do

    inherit! :search_paths
    # Pods for testing
  end

end
