# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Terra' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Terra
 pod 'Firebase/Firestore'
 pod 'Firebase/Storage'
 pod 'FirebaseUI/Storage'
 pod 'BATabBarController', '~> 2.0.0'
 

  target 'TerraTests' do

    inherit! :search_paths
    # Pods for testing
  end

end
